# Generated by Django 5.2.6 on 2026-04-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvcfcApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('vnpay', 'VNPay')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
